version: '3.9'
services:
  psql:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432

  elasticsearch:
    image: elasticsearch:7.10.1
    environment:
      discovery.type: single-node
    ports:
      - 9200:9200
      - 9300:9300
